// Code generated by eventsV2. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package eventsv2

import (
	"github.com/bwmarrin/discordgo"
)

type Event int

const (
	EventApplicationCommandPermissionsUpdate Event = 0
	EventAutoModerationActionExecution       Event = 1
	EventAutoModerationRuleCreate            Event = 2
	EventAutoModerationRuleDelete            Event = 3
	EventAutoModerationRuleUpdate            Event = 4
	EventChannelCreate                       Event = 5
	EventChannelDelete                       Event = 6
	EventChannelPinsUpdate                   Event = 7
	EventChannelUpdate                       Event = 8
	EventConnect                             Event = 9
	EventDisconnect                          Event = 10
	EventEntitlementCreate                   Event = 11
	EventEntitlementDelete                   Event = 12
	EventEntitlementUpdate                   Event = 13
	EventGuildAuditLogEntryCreate            Event = 14
	EventGuildBanAdd                         Event = 15
	EventGuildBanRemove                      Event = 16
	EventGuildCreate                         Event = 17
	EventGuildDelete                         Event = 18
	EventGuildEmojisUpdate                   Event = 19
	EventGuildIntegrationsUpdate             Event = 20
	EventGuildMemberAdd                      Event = 21
	EventGuildMemberRemove                   Event = 22
	EventGuildMemberUpdate                   Event = 23
	EventGuildMembersChunk                   Event = 24
	EventGuildRoleCreate                     Event = 25
	EventGuildRoleDelete                     Event = 26
	EventGuildRoleUpdate                     Event = 27
	EventGuildScheduledEventCreate           Event = 28
	EventGuildScheduledEventDelete           Event = 29
	EventGuildScheduledEventUpdate           Event = 30
	EventGuildScheduledEventUserAdd          Event = 31
	EventGuildScheduledEventUserRemove       Event = 32
	EventGuildStickersUpdate                 Event = 33
	EventGuildUpdate                         Event = 34
	EventIntegrationCreate                   Event = 35
	EventIntegrationDelete                   Event = 36
	EventIntegrationUpdate                   Event = 37
	EventInteractionCreate                   Event = 38
	EventInviteCreate                        Event = 39
	EventInviteDelete                        Event = 40
	EventMessageCreate                       Event = 41
	EventMessageDelete                       Event = 42
	EventMessageDeleteBulk                   Event = 43
	EventMessagePollVoteAdd                  Event = 44
	EventMessagePollVoteRemove               Event = 45
	EventMessageReactionAdd                  Event = 46
	EventMessageReactionRemove               Event = 47
	EventMessageReactionRemoveAll            Event = 48
	EventMessageUpdate                       Event = 49
	EventPresenceUpdate                      Event = 50
	EventPresencesReplace                    Event = 51
	EventRateLimit                           Event = 52
	EventReady                               Event = 53
	EventResumed                             Event = 54
	EventStageInstanceEventCreate            Event = 55
	EventStageInstanceEventDelete            Event = 56
	EventStageInstanceEventUpdate            Event = 57
	EventSubscriptionCreate                  Event = 58
	EventSubscriptionDelete                  Event = 59
	EventSubscriptionUpdate                  Event = 60
	EventThreadCreate                        Event = 61
	EventThreadDelete                        Event = 62
	EventThreadListSync                      Event = 63
	EventThreadMemberUpdate                  Event = 64
	EventThreadMembersUpdate                 Event = 65
	EventThreadUpdate                        Event = 66
	EventTypingStart                         Event = 67
	EventUserUpdate                          Event = 68
	EventVoiceServerUpdate                   Event = 69
	EventVoiceStateUpdate                    Event = 70
	EventWebhooksUpdate                      Event = 71
)

var AllDiscordEvents = []Event{
	EventApplicationCommandPermissionsUpdate,
	EventAutoModerationActionExecution,
	EventAutoModerationRuleCreate,
	EventAutoModerationRuleDelete,
	EventAutoModerationRuleUpdate,
	EventChannelCreate,
	EventChannelDelete,
	EventChannelPinsUpdate,
	EventChannelUpdate,
	EventConnect,
	EventDisconnect,
	EventEntitlementCreate,
	EventEntitlementDelete,
	EventEntitlementUpdate,
	EventGuildAuditLogEntryCreate,
	EventGuildBanAdd,
	EventGuildBanRemove,
	EventGuildCreate,
	EventGuildDelete,
	EventGuildEmojisUpdate,
	EventGuildIntegrationsUpdate,
	EventGuildMemberAdd,
	EventGuildMemberRemove,
	EventGuildMemberUpdate,
	EventGuildMembersChunk,
	EventGuildRoleCreate,
	EventGuildRoleDelete,
	EventGuildRoleUpdate,
	EventGuildScheduledEventCreate,
	EventGuildScheduledEventDelete,
	EventGuildScheduledEventUpdate,
	EventGuildScheduledEventUserAdd,
	EventGuildScheduledEventUserRemove,
	EventGuildStickersUpdate,
	EventGuildUpdate,
	EventIntegrationCreate,
	EventIntegrationDelete,
	EventIntegrationUpdate,
	EventInteractionCreate,
	EventInviteCreate,
	EventInviteDelete,
	EventMessageCreate,
	EventMessageDelete,
	EventMessageDeleteBulk,
	EventMessagePollVoteAdd,
	EventMessagePollVoteRemove,
	EventMessageReactionAdd,
	EventMessageReactionRemove,
	EventMessageReactionRemoveAll,
	EventMessageUpdate,
	EventPresenceUpdate,
	EventPresencesReplace,
	EventRateLimit,
	EventReady,
	EventResumed,
	EventStageInstanceEventCreate,
	EventStageInstanceEventDelete,
	EventStageInstanceEventUpdate,
	EventSubscriptionCreate,
	EventSubscriptionDelete,
	EventSubscriptionUpdate,
	EventThreadCreate,
	EventThreadDelete,
	EventThreadListSync,
	EventThreadMemberUpdate,
	EventThreadMembersUpdate,
	EventThreadUpdate,
	EventTypingStart,
	EventUserUpdate,
	EventVoiceServerUpdate,
	EventVoiceStateUpdate,
	EventWebhooksUpdate,
}

func (data *EventData) ApplicationCommandPermissionsUpdate() *discordgo.ApplicationCommandPermissionsUpdate {
	return data.Interface.(*discordgo.ApplicationCommandPermissionsUpdate)
}
func (data *EventData) AutoModerationActionExecution() *discordgo.AutoModerationActionExecution {
	return data.Interface.(*discordgo.AutoModerationActionExecution)
}
func (data *EventData) AutoModerationRuleCreate() *discordgo.AutoModerationRuleCreate {
	return data.Interface.(*discordgo.AutoModerationRuleCreate)
}
func (data *EventData) AutoModerationRuleDelete() *discordgo.AutoModerationRuleDelete {
	return data.Interface.(*discordgo.AutoModerationRuleDelete)
}
func (data *EventData) AutoModerationRuleUpdate() *discordgo.AutoModerationRuleUpdate {
	return data.Interface.(*discordgo.AutoModerationRuleUpdate)
}
func (data *EventData) ChannelCreate() *discordgo.ChannelCreate {
	return data.Interface.(*discordgo.ChannelCreate)
}
func (data *EventData) ChannelDelete() *discordgo.ChannelDelete {
	return data.Interface.(*discordgo.ChannelDelete)
}
func (data *EventData) ChannelPinsUpdate() *discordgo.ChannelPinsUpdate {
	return data.Interface.(*discordgo.ChannelPinsUpdate)
}
func (data *EventData) ChannelUpdate() *discordgo.ChannelUpdate {
	return data.Interface.(*discordgo.ChannelUpdate)
}
func (data *EventData) Connect() *discordgo.Connect {
	return data.Interface.(*discordgo.Connect)
}
func (data *EventData) Disconnect() *discordgo.Disconnect {
	return data.Interface.(*discordgo.Disconnect)
}
func (data *EventData) EntitlementCreate() *discordgo.EntitlementCreate {
	return data.Interface.(*discordgo.EntitlementCreate)
}
func (data *EventData) EntitlementDelete() *discordgo.EntitlementDelete {
	return data.Interface.(*discordgo.EntitlementDelete)
}
func (data *EventData) EntitlementUpdate() *discordgo.EntitlementUpdate {
	return data.Interface.(*discordgo.EntitlementUpdate)
}
func (data *EventData) GuildAuditLogEntryCreate() *discordgo.GuildAuditLogEntryCreate {
	return data.Interface.(*discordgo.GuildAuditLogEntryCreate)
}
func (data *EventData) GuildBanAdd() *discordgo.GuildBanAdd {
	return data.Interface.(*discordgo.GuildBanAdd)
}
func (data *EventData) GuildBanRemove() *discordgo.GuildBanRemove {
	return data.Interface.(*discordgo.GuildBanRemove)
}
func (data *EventData) GuildCreate() *discordgo.GuildCreate {
	return data.Interface.(*discordgo.GuildCreate)
}
func (data *EventData) GuildDelete() *discordgo.GuildDelete {
	return data.Interface.(*discordgo.GuildDelete)
}
func (data *EventData) GuildEmojisUpdate() *discordgo.GuildEmojisUpdate {
	return data.Interface.(*discordgo.GuildEmojisUpdate)
}
func (data *EventData) GuildIntegrationsUpdate() *discordgo.GuildIntegrationsUpdate {
	return data.Interface.(*discordgo.GuildIntegrationsUpdate)
}
func (data *EventData) GuildMemberAdd() *discordgo.GuildMemberAdd {
	return data.Interface.(*discordgo.GuildMemberAdd)
}
func (data *EventData) GuildMemberRemove() *discordgo.GuildMemberRemove {
	return data.Interface.(*discordgo.GuildMemberRemove)
}
func (data *EventData) GuildMemberUpdate() *discordgo.GuildMemberUpdate {
	return data.Interface.(*discordgo.GuildMemberUpdate)
}
func (data *EventData) GuildMembersChunk() *discordgo.GuildMembersChunk {
	return data.Interface.(*discordgo.GuildMembersChunk)
}
func (data *EventData) GuildRoleCreate() *discordgo.GuildRoleCreate {
	return data.Interface.(*discordgo.GuildRoleCreate)
}
func (data *EventData) GuildRoleDelete() *discordgo.GuildRoleDelete {
	return data.Interface.(*discordgo.GuildRoleDelete)
}
func (data *EventData) GuildRoleUpdate() *discordgo.GuildRoleUpdate {
	return data.Interface.(*discordgo.GuildRoleUpdate)
}
func (data *EventData) GuildScheduledEventCreate() *discordgo.GuildScheduledEventCreate {
	return data.Interface.(*discordgo.GuildScheduledEventCreate)
}
func (data *EventData) GuildScheduledEventDelete() *discordgo.GuildScheduledEventDelete {
	return data.Interface.(*discordgo.GuildScheduledEventDelete)
}
func (data *EventData) GuildScheduledEventUpdate() *discordgo.GuildScheduledEventUpdate {
	return data.Interface.(*discordgo.GuildScheduledEventUpdate)
}
func (data *EventData) GuildScheduledEventUserAdd() *discordgo.GuildScheduledEventUserAdd {
	return data.Interface.(*discordgo.GuildScheduledEventUserAdd)
}
func (data *EventData) GuildScheduledEventUserRemove() *discordgo.GuildScheduledEventUserRemove {
	return data.Interface.(*discordgo.GuildScheduledEventUserRemove)
}
func (data *EventData) GuildStickersUpdate() *discordgo.GuildStickersUpdate {
	return data.Interface.(*discordgo.GuildStickersUpdate)
}
func (data *EventData) GuildUpdate() *discordgo.GuildUpdate {
	return data.Interface.(*discordgo.GuildUpdate)
}
func (data *EventData) IntegrationCreate() *discordgo.IntegrationCreate {
	return data.Interface.(*discordgo.IntegrationCreate)
}
func (data *EventData) IntegrationDelete() *discordgo.IntegrationDelete {
	return data.Interface.(*discordgo.IntegrationDelete)
}
func (data *EventData) IntegrationUpdate() *discordgo.IntegrationUpdate {
	return data.Interface.(*discordgo.IntegrationUpdate)
}
func (data *EventData) InteractionCreate() *discordgo.InteractionCreate {
	return data.Interface.(*discordgo.InteractionCreate)
}
func (data *EventData) InviteCreate() *discordgo.InviteCreate {
	return data.Interface.(*discordgo.InviteCreate)
}
func (data *EventData) InviteDelete() *discordgo.InviteDelete {
	return data.Interface.(*discordgo.InviteDelete)
}
func (data *EventData) MessageCreate() *discordgo.MessageCreate {
	return data.Interface.(*discordgo.MessageCreate)
}
func (data *EventData) MessageDelete() *discordgo.MessageDelete {
	return data.Interface.(*discordgo.MessageDelete)
}
func (data *EventData) MessageDeleteBulk() *discordgo.MessageDeleteBulk {
	return data.Interface.(*discordgo.MessageDeleteBulk)
}
func (data *EventData) MessagePollVoteAdd() *discordgo.MessagePollVoteAdd {
	return data.Interface.(*discordgo.MessagePollVoteAdd)
}
func (data *EventData) MessagePollVoteRemove() *discordgo.MessagePollVoteRemove {
	return data.Interface.(*discordgo.MessagePollVoteRemove)
}
func (data *EventData) MessageReactionAdd() *discordgo.MessageReactionAdd {
	return data.Interface.(*discordgo.MessageReactionAdd)
}
func (data *EventData) MessageReactionRemove() *discordgo.MessageReactionRemove {
	return data.Interface.(*discordgo.MessageReactionRemove)
}
func (data *EventData) MessageReactionRemoveAll() *discordgo.MessageReactionRemoveAll {
	return data.Interface.(*discordgo.MessageReactionRemoveAll)
}
func (data *EventData) MessageUpdate() *discordgo.MessageUpdate {
	return data.Interface.(*discordgo.MessageUpdate)
}
func (data *EventData) PresenceUpdate() *discordgo.PresenceUpdate {
	return data.Interface.(*discordgo.PresenceUpdate)
}
func (data *EventData) PresencesReplace() *discordgo.PresencesReplace {
	return data.Interface.(*discordgo.PresencesReplace)
}
func (data *EventData) RateLimit() *discordgo.RateLimit {
	return data.Interface.(*discordgo.RateLimit)
}
func (data *EventData) Ready() *discordgo.Ready {
	return data.Interface.(*discordgo.Ready)
}
func (data *EventData) Resumed() *discordgo.Resumed {
	return data.Interface.(*discordgo.Resumed)
}
func (data *EventData) StageInstanceEventCreate() *discordgo.StageInstanceEventCreate {
	return data.Interface.(*discordgo.StageInstanceEventCreate)
}
func (data *EventData) StageInstanceEventDelete() *discordgo.StageInstanceEventDelete {
	return data.Interface.(*discordgo.StageInstanceEventDelete)
}
func (data *EventData) StageInstanceEventUpdate() *discordgo.StageInstanceEventUpdate {
	return data.Interface.(*discordgo.StageInstanceEventUpdate)
}
func (data *EventData) SubscriptionCreate() *discordgo.SubscriptionCreate {
	return data.Interface.(*discordgo.SubscriptionCreate)
}
func (data *EventData) SubscriptionDelete() *discordgo.SubscriptionDelete {
	return data.Interface.(*discordgo.SubscriptionDelete)
}
func (data *EventData) SubscriptionUpdate() *discordgo.SubscriptionUpdate {
	return data.Interface.(*discordgo.SubscriptionUpdate)
}
func (data *EventData) ThreadCreate() *discordgo.ThreadCreate {
	return data.Interface.(*discordgo.ThreadCreate)
}
func (data *EventData) ThreadDelete() *discordgo.ThreadDelete {
	return data.Interface.(*discordgo.ThreadDelete)
}
func (data *EventData) ThreadListSync() *discordgo.ThreadListSync {
	return data.Interface.(*discordgo.ThreadListSync)
}
func (data *EventData) ThreadMemberUpdate() *discordgo.ThreadMemberUpdate {
	return data.Interface.(*discordgo.ThreadMemberUpdate)
}
func (data *EventData) ThreadMembersUpdate() *discordgo.ThreadMembersUpdate {
	return data.Interface.(*discordgo.ThreadMembersUpdate)
}
func (data *EventData) ThreadUpdate() *discordgo.ThreadUpdate {
	return data.Interface.(*discordgo.ThreadUpdate)
}
func (data *EventData) TypingStart() *discordgo.TypingStart {
	return data.Interface.(*discordgo.TypingStart)
}
func (data *EventData) UserUpdate() *discordgo.UserUpdate {
	return data.Interface.(*discordgo.UserUpdate)
}
func (data *EventData) VoiceServerUpdate() *discordgo.VoiceServerUpdate {
	return data.Interface.(*discordgo.VoiceServerUpdate)
}
func (data *EventData) VoiceStateUpdate() *discordgo.VoiceStateUpdate {
	return data.Interface.(*discordgo.VoiceStateUpdate)
}
func (data *EventData) WebhooksUpdate() *discordgo.WebhooksUpdate {
	return data.Interface.(*discordgo.WebhooksUpdate)
}

func setEventType(data *EventData) {

	switch data.Interface.(type) {
	case *discordgo.ApplicationCommandPermissionsUpdate:
		data.Type = EventApplicationCommandPermissionsUpdate
	case *discordgo.AutoModerationActionExecution:
		data.Type = EventAutoModerationActionExecution
	case *discordgo.AutoModerationRuleCreate:
		data.Type = EventAutoModerationRuleCreate
	case *discordgo.AutoModerationRuleDelete:
		data.Type = EventAutoModerationRuleDelete
	case *discordgo.AutoModerationRuleUpdate:
		data.Type = EventAutoModerationRuleUpdate
	case *discordgo.ChannelCreate:
		data.Type = EventChannelCreate
	case *discordgo.ChannelDelete:
		data.Type = EventChannelDelete
	case *discordgo.ChannelPinsUpdate:
		data.Type = EventChannelPinsUpdate
	case *discordgo.ChannelUpdate:
		data.Type = EventChannelUpdate
	case *discordgo.Connect:
		data.Type = EventConnect
	case *discordgo.Disconnect:
		data.Type = EventDisconnect
	case *discordgo.EntitlementCreate:
		data.Type = EventEntitlementCreate
	case *discordgo.EntitlementDelete:
		data.Type = EventEntitlementDelete
	case *discordgo.EntitlementUpdate:
		data.Type = EventEntitlementUpdate
	case *discordgo.GuildAuditLogEntryCreate:
		data.Type = EventGuildAuditLogEntryCreate
	case *discordgo.GuildBanAdd:
		data.Type = EventGuildBanAdd
	case *discordgo.GuildBanRemove:
		data.Type = EventGuildBanRemove
	case *discordgo.GuildCreate:
		data.Type = EventGuildCreate
	case *discordgo.GuildDelete:
		data.Type = EventGuildDelete
	case *discordgo.GuildEmojisUpdate:
		data.Type = EventGuildEmojisUpdate
	case *discordgo.GuildIntegrationsUpdate:
		data.Type = EventGuildIntegrationsUpdate
	case *discordgo.GuildMemberAdd:
		data.Type = EventGuildMemberAdd
	case *discordgo.GuildMemberRemove:
		data.Type = EventGuildMemberRemove
	case *discordgo.GuildMemberUpdate:
		data.Type = EventGuildMemberUpdate
	case *discordgo.GuildMembersChunk:
		data.Type = EventGuildMembersChunk
	case *discordgo.GuildRoleCreate:
		data.Type = EventGuildRoleCreate
	case *discordgo.GuildRoleDelete:
		data.Type = EventGuildRoleDelete
	case *discordgo.GuildRoleUpdate:
		data.Type = EventGuildRoleUpdate
	case *discordgo.GuildScheduledEventCreate:
		data.Type = EventGuildScheduledEventCreate
	case *discordgo.GuildScheduledEventDelete:
		data.Type = EventGuildScheduledEventDelete
	case *discordgo.GuildScheduledEventUpdate:
		data.Type = EventGuildScheduledEventUpdate
	case *discordgo.GuildScheduledEventUserAdd:
		data.Type = EventGuildScheduledEventUserAdd
	case *discordgo.GuildScheduledEventUserRemove:
		data.Type = EventGuildScheduledEventUserRemove
	case *discordgo.GuildStickersUpdate:
		data.Type = EventGuildStickersUpdate
	case *discordgo.GuildUpdate:
		data.Type = EventGuildUpdate
	case *discordgo.IntegrationCreate:
		data.Type = EventIntegrationCreate
	case *discordgo.IntegrationDelete:
		data.Type = EventIntegrationDelete
	case *discordgo.IntegrationUpdate:
		data.Type = EventIntegrationUpdate
	case *discordgo.InteractionCreate:
		data.Type = EventInteractionCreate
	case *discordgo.InviteCreate:
		data.Type = EventInviteCreate
	case *discordgo.InviteDelete:
		data.Type = EventInviteDelete
	case *discordgo.MessageCreate:
		data.Type = EventMessageCreate
	case *discordgo.MessageDelete:
		data.Type = EventMessageDelete
	case *discordgo.MessageDeleteBulk:
		data.Type = EventMessageDeleteBulk
	case *discordgo.MessagePollVoteAdd:
		data.Type = EventMessagePollVoteAdd
	case *discordgo.MessagePollVoteRemove:
		data.Type = EventMessagePollVoteRemove
	case *discordgo.MessageReactionAdd:
		data.Type = EventMessageReactionAdd
	case *discordgo.MessageReactionRemove:
		data.Type = EventMessageReactionRemove
	case *discordgo.MessageReactionRemoveAll:
		data.Type = EventMessageReactionRemoveAll
	case *discordgo.MessageUpdate:
		data.Type = EventMessageUpdate
	case *discordgo.PresenceUpdate:
		data.Type = EventPresenceUpdate
	case *discordgo.PresencesReplace:
		data.Type = EventPresencesReplace
	case *discordgo.RateLimit:
		data.Type = EventRateLimit
	case *discordgo.Ready:
		data.Type = EventReady
	case *discordgo.Resumed:
		data.Type = EventResumed
	case *discordgo.StageInstanceEventCreate:
		data.Type = EventStageInstanceEventCreate
	case *discordgo.StageInstanceEventDelete:
		data.Type = EventStageInstanceEventDelete
	case *discordgo.StageInstanceEventUpdate:
		data.Type = EventStageInstanceEventUpdate
	case *discordgo.SubscriptionCreate:
		data.Type = EventSubscriptionCreate
	case *discordgo.SubscriptionDelete:
		data.Type = EventSubscriptionDelete
	case *discordgo.SubscriptionUpdate:
		data.Type = EventSubscriptionUpdate
	case *discordgo.ThreadCreate:
		data.Type = EventThreadCreate
	case *discordgo.ThreadDelete:
		data.Type = EventThreadDelete
	case *discordgo.ThreadListSync:
		data.Type = EventThreadListSync
	case *discordgo.ThreadMemberUpdate:
		data.Type = EventThreadMemberUpdate
	case *discordgo.ThreadMembersUpdate:
		data.Type = EventThreadMembersUpdate
	case *discordgo.ThreadUpdate:
		data.Type = EventThreadUpdate
	case *discordgo.TypingStart:
		data.Type = EventTypingStart
	case *discordgo.UserUpdate:
		data.Type = EventUserUpdate
	case *discordgo.VoiceServerUpdate:
		data.Type = EventVoiceServerUpdate
	case *discordgo.VoiceStateUpdate:
		data.Type = EventVoiceStateUpdate
	case *discordgo.WebhooksUpdate:
		data.Type = EventWebhooksUpdate
	default:
		return
	}

	return
}
