// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ModerationMessageLog is an object representing the database table.
type ModerationMessageLog struct {
	ID             int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	GuildID        string    `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	CaseID         int64     `boil:"case_id" json:"case_id" toml:"case_id" yaml:"case_id"`
	ChannelID      string    `boil:"channel_id" json:"channel_id" toml:"channel_id" yaml:"channel_id"`
	ChannelName    string    `boil:"channel_name" json:"channel_name" toml:"channel_name" yaml:"channel_name"`
	AuthorID       string    `boil:"author_id" json:"author_id" toml:"author_id" yaml:"author_id"`
	AuthorUsername string    `boil:"author_username" json:"author_username" toml:"author_username" yaml:"author_username"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *moderationMessageLogR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L moderationMessageLogL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ModerationMessageLogColumns = struct {
	ID             string
	GuildID        string
	CaseID         string
	ChannelID      string
	ChannelName    string
	AuthorID       string
	AuthorUsername string
	CreatedAt      string
}{
	ID:             "id",
	GuildID:        "guild_id",
	CaseID:         "case_id",
	ChannelID:      "channel_id",
	ChannelName:    "channel_name",
	AuthorID:       "author_id",
	AuthorUsername: "author_username",
	CreatedAt:      "created_at",
}

var ModerationMessageLogTableColumns = struct {
	ID             string
	GuildID        string
	CaseID         string
	ChannelID      string
	ChannelName    string
	AuthorID       string
	AuthorUsername string
	CreatedAt      string
}{
	ID:             "moderation_message_logs.id",
	GuildID:        "moderation_message_logs.guild_id",
	CaseID:         "moderation_message_logs.case_id",
	ChannelID:      "moderation_message_logs.channel_id",
	ChannelName:    "moderation_message_logs.channel_name",
	AuthorID:       "moderation_message_logs.author_id",
	AuthorUsername: "moderation_message_logs.author_username",
	CreatedAt:      "moderation_message_logs.created_at",
}

// Generated where

var ModerationMessageLogWhere = struct {
	ID             whereHelperint64
	GuildID        whereHelperstring
	CaseID         whereHelperint64
	ChannelID      whereHelperstring
	ChannelName    whereHelperstring
	AuthorID       whereHelperstring
	AuthorUsername whereHelperstring
	CreatedAt      whereHelpertime_Time
}{
	ID:             whereHelperint64{field: "\"moderation_message_logs\".\"id\""},
	GuildID:        whereHelperstring{field: "\"moderation_message_logs\".\"guild_id\""},
	CaseID:         whereHelperint64{field: "\"moderation_message_logs\".\"case_id\""},
	ChannelID:      whereHelperstring{field: "\"moderation_message_logs\".\"channel_id\""},
	ChannelName:    whereHelperstring{field: "\"moderation_message_logs\".\"channel_name\""},
	AuthorID:       whereHelperstring{field: "\"moderation_message_logs\".\"author_id\""},
	AuthorUsername: whereHelperstring{field: "\"moderation_message_logs\".\"author_username\""},
	CreatedAt:      whereHelpertime_Time{field: "\"moderation_message_logs\".\"created_at\""},
}

// ModerationMessageLogRels is where relationship names are stored.
var ModerationMessageLogRels = struct {
	LogModerationMessageLogsMessages string
}{
	LogModerationMessageLogsMessages: "LogModerationMessageLogsMessages",
}

// moderationMessageLogR is where relationships are stored.
type moderationMessageLogR struct {
	LogModerationMessageLogsMessages ModerationMessageLogsMessageSlice `boil:"LogModerationMessageLogsMessages" json:"LogModerationMessageLogsMessages" toml:"LogModerationMessageLogsMessages" yaml:"LogModerationMessageLogsMessages"`
}

// NewStruct creates a new relationship struct
func (*moderationMessageLogR) NewStruct() *moderationMessageLogR {
	return &moderationMessageLogR{}
}

func (o *ModerationMessageLog) GetLogModerationMessageLogsMessages() ModerationMessageLogsMessageSlice {
	if o == nil {
		return nil
	}

	return o.R.GetLogModerationMessageLogsMessages()
}

func (r *moderationMessageLogR) GetLogModerationMessageLogsMessages() ModerationMessageLogsMessageSlice {
	if r == nil {
		return nil
	}

	return r.LogModerationMessageLogsMessages
}

// moderationMessageLogL is where Load methods for each relationship are stored.
type moderationMessageLogL struct{}

var (
	moderationMessageLogAllColumns            = []string{"id", "guild_id", "case_id", "channel_id", "channel_name", "author_id", "author_username", "created_at"}
	moderationMessageLogColumnsWithoutDefault = []string{"guild_id", "case_id", "channel_id", "channel_name", "author_id", "author_username", "created_at"}
	moderationMessageLogColumnsWithDefault    = []string{"id"}
	moderationMessageLogPrimaryKeyColumns     = []string{"id"}
	moderationMessageLogGeneratedColumns      = []string{}
)

type (
	// ModerationMessageLogSlice is an alias for a slice of pointers to ModerationMessageLog.
	// This should almost always be used instead of []ModerationMessageLog.
	ModerationMessageLogSlice []*ModerationMessageLog

	moderationMessageLogQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	moderationMessageLogType                 = reflect.TypeOf(&ModerationMessageLog{})
	moderationMessageLogMapping              = queries.MakeStructMapping(moderationMessageLogType)
	moderationMessageLogPrimaryKeyMapping, _ = queries.BindMapping(moderationMessageLogType, moderationMessageLogMapping, moderationMessageLogPrimaryKeyColumns)
	moderationMessageLogInsertCacheMut       sync.RWMutex
	moderationMessageLogInsertCache          = make(map[string]insertCache)
	moderationMessageLogUpdateCacheMut       sync.RWMutex
	moderationMessageLogUpdateCache          = make(map[string]updateCache)
	moderationMessageLogUpsertCacheMut       sync.RWMutex
	moderationMessageLogUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single moderationMessageLog record from the query using the global executor.
func (q moderationMessageLogQuery) OneG(ctx context.Context) (*ModerationMessageLog, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single moderationMessageLog record from the query.
func (q moderationMessageLogQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ModerationMessageLog, error) {
	o := &ModerationMessageLog{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for moderation_message_logs")
	}

	return o, nil
}

// AllG returns all ModerationMessageLog records from the query using the global executor.
func (q moderationMessageLogQuery) AllG(ctx context.Context) (ModerationMessageLogSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ModerationMessageLog records from the query.
func (q moderationMessageLogQuery) All(ctx context.Context, exec boil.ContextExecutor) (ModerationMessageLogSlice, error) {
	var o []*ModerationMessageLog

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ModerationMessageLog slice")
	}

	return o, nil
}

// CountG returns the count of all ModerationMessageLog records in the query using the global executor
func (q moderationMessageLogQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ModerationMessageLog records in the query.
func (q moderationMessageLogQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count moderation_message_logs rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q moderationMessageLogQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q moderationMessageLogQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if moderation_message_logs exists")
	}

	return count > 0, nil
}

// LogModerationMessageLogsMessages retrieves all the moderation_message_logs_message's ModerationMessageLogsMessages with an executor via log_id column.
func (o *ModerationMessageLog) LogModerationMessageLogsMessages(mods ...qm.QueryMod) moderationMessageLogsMessageQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"moderation_message_logs_messages\".\"log_id\"=?", o.ID),
	)

	return ModerationMessageLogsMessages(queryMods...)
}

// LoadLogModerationMessageLogsMessages allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (moderationMessageLogL) LoadLogModerationMessageLogsMessages(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModerationMessageLog interface{}, mods queries.Applicator) error {
	var slice []*ModerationMessageLog
	var object *ModerationMessageLog

	if singular {
		var ok bool
		object, ok = maybeModerationMessageLog.(*ModerationMessageLog)
		if !ok {
			object = new(ModerationMessageLog)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModerationMessageLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModerationMessageLog))
			}
		}
	} else {
		s, ok := maybeModerationMessageLog.(*[]*ModerationMessageLog)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModerationMessageLog)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModerationMessageLog))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &moderationMessageLogR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moderationMessageLogR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`moderation_message_logs_messages`),
		qm.WhereIn(`moderation_message_logs_messages.log_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load moderation_message_logs_messages")
	}

	var resultSlice []*ModerationMessageLogsMessage
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice moderation_message_logs_messages")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on moderation_message_logs_messages")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for moderation_message_logs_messages")
	}

	if singular {
		object.R.LogModerationMessageLogsMessages = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &moderationMessageLogsMessageR{}
			}
			foreign.R.Log = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.LogID {
				local.R.LogModerationMessageLogsMessages = append(local.R.LogModerationMessageLogsMessages, foreign)
				if foreign.R == nil {
					foreign.R = &moderationMessageLogsMessageR{}
				}
				foreign.R.Log = local
				break
			}
		}
	}

	return nil
}

// AddLogModerationMessageLogsMessagesG adds the given related objects to the existing relationships
// of the moderation_message_log, optionally inserting them as new records.
// Appends related to o.R.LogModerationMessageLogsMessages.
// Sets related.R.Log appropriately.
// Uses the global database handle.
func (o *ModerationMessageLog) AddLogModerationMessageLogsMessagesG(ctx context.Context, insert bool, related ...*ModerationMessageLogsMessage) error {
	return o.AddLogModerationMessageLogsMessages(ctx, boil.GetContextDB(), insert, related...)
}

// AddLogModerationMessageLogsMessages adds the given related objects to the existing relationships
// of the moderation_message_log, optionally inserting them as new records.
// Appends related to o.R.LogModerationMessageLogsMessages.
// Sets related.R.Log appropriately.
func (o *ModerationMessageLog) AddLogModerationMessageLogsMessages(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*ModerationMessageLogsMessage) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.LogID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"moderation_message_logs_messages\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"log_id"}),
				strmangle.WhereClause("\"", "\"", 2, moderationMessageLogsMessagePrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.LogID = o.ID
		}
	}

	if o.R == nil {
		o.R = &moderationMessageLogR{
			LogModerationMessageLogsMessages: related,
		}
	} else {
		o.R.LogModerationMessageLogsMessages = append(o.R.LogModerationMessageLogsMessages, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &moderationMessageLogsMessageR{
				Log: o,
			}
		} else {
			rel.R.Log = o
		}
	}
	return nil
}

// ModerationMessageLogs retrieves all the records using an executor.
func ModerationMessageLogs(mods ...qm.QueryMod) moderationMessageLogQuery {
	mods = append(mods, qm.From("\"moderation_message_logs\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"moderation_message_logs\".*"})
	}

	return moderationMessageLogQuery{q}
}

// FindModerationMessageLogG retrieves a single record by ID.
func FindModerationMessageLogG(ctx context.Context, iD int64, selectCols ...string) (*ModerationMessageLog, error) {
	return FindModerationMessageLog(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindModerationMessageLog retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindModerationMessageLog(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ModerationMessageLog, error) {
	moderationMessageLogObj := &ModerationMessageLog{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"moderation_message_logs\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, moderationMessageLogObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from moderation_message_logs")
	}

	return moderationMessageLogObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ModerationMessageLog) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ModerationMessageLog) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no moderation_message_logs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(moderationMessageLogColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	moderationMessageLogInsertCacheMut.RLock()
	cache, cached := moderationMessageLogInsertCache[key]
	moderationMessageLogInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			moderationMessageLogAllColumns,
			moderationMessageLogColumnsWithDefault,
			moderationMessageLogColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(moderationMessageLogType, moderationMessageLogMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(moderationMessageLogType, moderationMessageLogMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"moderation_message_logs\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"moderation_message_logs\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into moderation_message_logs")
	}

	if !cached {
		moderationMessageLogInsertCacheMut.Lock()
		moderationMessageLogInsertCache[key] = cache
		moderationMessageLogInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single ModerationMessageLog record using the global executor.
// See Update for more documentation.
func (o *ModerationMessageLog) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ModerationMessageLog.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ModerationMessageLog) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	moderationMessageLogUpdateCacheMut.RLock()
	cache, cached := moderationMessageLogUpdateCache[key]
	moderationMessageLogUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			moderationMessageLogAllColumns,
			moderationMessageLogPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update moderation_message_logs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"moderation_message_logs\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, moderationMessageLogPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(moderationMessageLogType, moderationMessageLogMapping, append(wl, moderationMessageLogPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update moderation_message_logs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for moderation_message_logs")
	}

	if !cached {
		moderationMessageLogUpdateCacheMut.Lock()
		moderationMessageLogUpdateCache[key] = cache
		moderationMessageLogUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q moderationMessageLogQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q moderationMessageLogQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for moderation_message_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for moderation_message_logs")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ModerationMessageLogSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ModerationMessageLogSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationMessageLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"moderation_message_logs\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, moderationMessageLogPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in moderationMessageLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all moderationMessageLog")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ModerationMessageLog) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ModerationMessageLog) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no moderation_message_logs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(moderationMessageLogColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	moderationMessageLogUpsertCacheMut.RLock()
	cache, cached := moderationMessageLogUpsertCache[key]
	moderationMessageLogUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			moderationMessageLogAllColumns,
			moderationMessageLogColumnsWithDefault,
			moderationMessageLogColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			moderationMessageLogAllColumns,
			moderationMessageLogPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert moderation_message_logs, could not build update column list")
		}

		ret := strmangle.SetComplement(moderationMessageLogAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(moderationMessageLogPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert moderation_message_logs, could not build conflict column list")
			}

			conflict = make([]string, len(moderationMessageLogPrimaryKeyColumns))
			copy(conflict, moderationMessageLogPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"moderation_message_logs\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(moderationMessageLogType, moderationMessageLogMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(moderationMessageLogType, moderationMessageLogMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert moderation_message_logs")
	}

	if !cached {
		moderationMessageLogUpsertCacheMut.Lock()
		moderationMessageLogUpsertCache[key] = cache
		moderationMessageLogUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single ModerationMessageLog record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ModerationMessageLog) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ModerationMessageLog record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ModerationMessageLog) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ModerationMessageLog provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), moderationMessageLogPrimaryKeyMapping)
	sql := "DELETE FROM \"moderation_message_logs\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from moderation_message_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for moderation_message_logs")
	}

	return rowsAff, nil
}

func (q moderationMessageLogQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q moderationMessageLogQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no moderationMessageLogQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderation_message_logs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_message_logs")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ModerationMessageLogSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ModerationMessageLogSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationMessageLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"moderation_message_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationMessageLogPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderationMessageLog slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_message_logs")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ModerationMessageLog) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no ModerationMessageLog provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ModerationMessageLog) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindModerationMessageLog(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationMessageLogSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty ModerationMessageLogSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationMessageLogSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ModerationMessageLogSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationMessageLogPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"moderation_message_logs\".* FROM \"moderation_message_logs\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationMessageLogPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ModerationMessageLogSlice")
	}

	*o = slice

	return nil
}

// ModerationMessageLogExistsG checks if the ModerationMessageLog row exists.
func ModerationMessageLogExistsG(ctx context.Context, iD int64) (bool, error) {
	return ModerationMessageLogExists(ctx, boil.GetContextDB(), iD)
}

// ModerationMessageLogExists checks if the ModerationMessageLog row exists.
func ModerationMessageLogExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"moderation_message_logs\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if moderation_message_logs exists")
	}

	return exists, nil
}

// Exists checks if the ModerationMessageLog row exists.
func (o *ModerationMessageLog) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ModerationMessageLogExists(ctx, exec, o.ID)
}
