// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// ModerationMessageLogsMessage is an object representing the database table.
type ModerationMessageLogsMessage struct {
	ID             int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	LogID          int64     `boil:"log_id" json:"log_id" toml:"log_id" yaml:"log_id"`
	GuildID        string    `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	AuthorID       string    `boil:"author_id" json:"author_id" toml:"author_id" yaml:"author_id"`
	AuthorUsername string    `boil:"author_username" json:"author_username" toml:"author_username" yaml:"author_username"`
	Content        string    `boil:"content" json:"content" toml:"content" yaml:"content"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	IsDeleted      bool      `boil:"is_deleted" json:"is_deleted" toml:"is_deleted" yaml:"is_deleted"`

	R *moderationMessageLogsMessageR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L moderationMessageLogsMessageL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ModerationMessageLogsMessageColumns = struct {
	ID             string
	LogID          string
	GuildID        string
	AuthorID       string
	AuthorUsername string
	Content        string
	CreatedAt      string
	IsDeleted      string
}{
	ID:             "id",
	LogID:          "log_id",
	GuildID:        "guild_id",
	AuthorID:       "author_id",
	AuthorUsername: "author_username",
	Content:        "content",
	CreatedAt:      "created_at",
	IsDeleted:      "is_deleted",
}

var ModerationMessageLogsMessageTableColumns = struct {
	ID             string
	LogID          string
	GuildID        string
	AuthorID       string
	AuthorUsername string
	Content        string
	CreatedAt      string
	IsDeleted      string
}{
	ID:             "moderation_message_logs_messages.id",
	LogID:          "moderation_message_logs_messages.log_id",
	GuildID:        "moderation_message_logs_messages.guild_id",
	AuthorID:       "moderation_message_logs_messages.author_id",
	AuthorUsername: "moderation_message_logs_messages.author_username",
	Content:        "moderation_message_logs_messages.content",
	CreatedAt:      "moderation_message_logs_messages.created_at",
	IsDeleted:      "moderation_message_logs_messages.is_deleted",
}

// Generated where

var ModerationMessageLogsMessageWhere = struct {
	ID             whereHelperint64
	LogID          whereHelperint64
	GuildID        whereHelperstring
	AuthorID       whereHelperstring
	AuthorUsername whereHelperstring
	Content        whereHelperstring
	CreatedAt      whereHelpertime_Time
	IsDeleted      whereHelperbool
}{
	ID:             whereHelperint64{field: "\"moderation_message_logs_messages\".\"id\""},
	LogID:          whereHelperint64{field: "\"moderation_message_logs_messages\".\"log_id\""},
	GuildID:        whereHelperstring{field: "\"moderation_message_logs_messages\".\"guild_id\""},
	AuthorID:       whereHelperstring{field: "\"moderation_message_logs_messages\".\"author_id\""},
	AuthorUsername: whereHelperstring{field: "\"moderation_message_logs_messages\".\"author_username\""},
	Content:        whereHelperstring{field: "\"moderation_message_logs_messages\".\"content\""},
	CreatedAt:      whereHelpertime_Time{field: "\"moderation_message_logs_messages\".\"created_at\""},
	IsDeleted:      whereHelperbool{field: "\"moderation_message_logs_messages\".\"is_deleted\""},
}

// ModerationMessageLogsMessageRels is where relationship names are stored.
var ModerationMessageLogsMessageRels = struct {
	Log string
}{
	Log: "Log",
}

// moderationMessageLogsMessageR is where relationships are stored.
type moderationMessageLogsMessageR struct {
	Log *ModerationMessageLog `boil:"Log" json:"Log" toml:"Log" yaml:"Log"`
}

// NewStruct creates a new relationship struct
func (*moderationMessageLogsMessageR) NewStruct() *moderationMessageLogsMessageR {
	return &moderationMessageLogsMessageR{}
}

func (o *ModerationMessageLogsMessage) GetLog() *ModerationMessageLog {
	if o == nil {
		return nil
	}

	return o.R.GetLog()
}

func (r *moderationMessageLogsMessageR) GetLog() *ModerationMessageLog {
	if r == nil {
		return nil
	}

	return r.Log
}

// moderationMessageLogsMessageL is where Load methods for each relationship are stored.
type moderationMessageLogsMessageL struct{}

var (
	moderationMessageLogsMessageAllColumns            = []string{"id", "log_id", "guild_id", "author_id", "author_username", "content", "created_at", "is_deleted"}
	moderationMessageLogsMessageColumnsWithoutDefault = []string{"log_id", "guild_id", "author_id", "author_username", "content", "created_at"}
	moderationMessageLogsMessageColumnsWithDefault    = []string{"id", "is_deleted"}
	moderationMessageLogsMessagePrimaryKeyColumns     = []string{"id"}
	moderationMessageLogsMessageGeneratedColumns      = []string{}
)

type (
	// ModerationMessageLogsMessageSlice is an alias for a slice of pointers to ModerationMessageLogsMessage.
	// This should almost always be used instead of []ModerationMessageLogsMessage.
	ModerationMessageLogsMessageSlice []*ModerationMessageLogsMessage

	moderationMessageLogsMessageQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	moderationMessageLogsMessageType                 = reflect.TypeOf(&ModerationMessageLogsMessage{})
	moderationMessageLogsMessageMapping              = queries.MakeStructMapping(moderationMessageLogsMessageType)
	moderationMessageLogsMessagePrimaryKeyMapping, _ = queries.BindMapping(moderationMessageLogsMessageType, moderationMessageLogsMessageMapping, moderationMessageLogsMessagePrimaryKeyColumns)
	moderationMessageLogsMessageInsertCacheMut       sync.RWMutex
	moderationMessageLogsMessageInsertCache          = make(map[string]insertCache)
	moderationMessageLogsMessageUpdateCacheMut       sync.RWMutex
	moderationMessageLogsMessageUpdateCache          = make(map[string]updateCache)
	moderationMessageLogsMessageUpsertCacheMut       sync.RWMutex
	moderationMessageLogsMessageUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single moderationMessageLogsMessage record from the query using the global executor.
func (q moderationMessageLogsMessageQuery) OneG(ctx context.Context) (*ModerationMessageLogsMessage, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single moderationMessageLogsMessage record from the query.
func (q moderationMessageLogsMessageQuery) One(ctx context.Context, exec boil.ContextExecutor) (*ModerationMessageLogsMessage, error) {
	o := &ModerationMessageLogsMessage{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for moderation_message_logs_messages")
	}

	return o, nil
}

// AllG returns all ModerationMessageLogsMessage records from the query using the global executor.
func (q moderationMessageLogsMessageQuery) AllG(ctx context.Context) (ModerationMessageLogsMessageSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all ModerationMessageLogsMessage records from the query.
func (q moderationMessageLogsMessageQuery) All(ctx context.Context, exec boil.ContextExecutor) (ModerationMessageLogsMessageSlice, error) {
	var o []*ModerationMessageLogsMessage

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to ModerationMessageLogsMessage slice")
	}

	return o, nil
}

// CountG returns the count of all ModerationMessageLogsMessage records in the query using the global executor
func (q moderationMessageLogsMessageQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all ModerationMessageLogsMessage records in the query.
func (q moderationMessageLogsMessageQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count moderation_message_logs_messages rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q moderationMessageLogsMessageQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q moderationMessageLogsMessageQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if moderation_message_logs_messages exists")
	}

	return count > 0, nil
}

// Log pointed to by the foreign key.
func (o *ModerationMessageLogsMessage) Log(mods ...qm.QueryMod) moderationMessageLogQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.LogID),
	}

	queryMods = append(queryMods, mods...)

	return ModerationMessageLogs(queryMods...)
}

// LoadLog allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (moderationMessageLogsMessageL) LoadLog(ctx context.Context, e boil.ContextExecutor, singular bool, maybeModerationMessageLogsMessage interface{}, mods queries.Applicator) error {
	var slice []*ModerationMessageLogsMessage
	var object *ModerationMessageLogsMessage

	if singular {
		var ok bool
		object, ok = maybeModerationMessageLogsMessage.(*ModerationMessageLogsMessage)
		if !ok {
			object = new(ModerationMessageLogsMessage)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeModerationMessageLogsMessage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeModerationMessageLogsMessage))
			}
		}
	} else {
		s, ok := maybeModerationMessageLogsMessage.(*[]*ModerationMessageLogsMessage)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeModerationMessageLogsMessage)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeModerationMessageLogsMessage))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &moderationMessageLogsMessageR{}
		}
		args[object.LogID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &moderationMessageLogsMessageR{}
			}

			args[obj.LogID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`moderation_message_logs`),
		qm.WhereIn(`moderation_message_logs.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ModerationMessageLog")
	}

	var resultSlice []*ModerationMessageLog
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ModerationMessageLog")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for moderation_message_logs")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for moderation_message_logs")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Log = foreign
		if foreign.R == nil {
			foreign.R = &moderationMessageLogR{}
		}
		foreign.R.LogModerationMessageLogsMessages = append(foreign.R.LogModerationMessageLogsMessages, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LogID == foreign.ID {
				local.R.Log = foreign
				if foreign.R == nil {
					foreign.R = &moderationMessageLogR{}
				}
				foreign.R.LogModerationMessageLogsMessages = append(foreign.R.LogModerationMessageLogsMessages, local)
				break
			}
		}
	}

	return nil
}

// SetLogG of the moderationMessageLogsMessage to the related item.
// Sets o.R.Log to related.
// Adds o to related.R.LogModerationMessageLogsMessages.
// Uses the global database handle.
func (o *ModerationMessageLogsMessage) SetLogG(ctx context.Context, insert bool, related *ModerationMessageLog) error {
	return o.SetLog(ctx, boil.GetContextDB(), insert, related)
}

// SetLog of the moderationMessageLogsMessage to the related item.
// Sets o.R.Log to related.
// Adds o to related.R.LogModerationMessageLogsMessages.
func (o *ModerationMessageLogsMessage) SetLog(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ModerationMessageLog) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"moderation_message_logs_messages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"log_id"}),
		strmangle.WhereClause("\"", "\"", 2, moderationMessageLogsMessagePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LogID = related.ID
	if o.R == nil {
		o.R = &moderationMessageLogsMessageR{
			Log: related,
		}
	} else {
		o.R.Log = related
	}

	if related.R == nil {
		related.R = &moderationMessageLogR{
			LogModerationMessageLogsMessages: ModerationMessageLogsMessageSlice{o},
		}
	} else {
		related.R.LogModerationMessageLogsMessages = append(related.R.LogModerationMessageLogsMessages, o)
	}

	return nil
}

// ModerationMessageLogsMessages retrieves all the records using an executor.
func ModerationMessageLogsMessages(mods ...qm.QueryMod) moderationMessageLogsMessageQuery {
	mods = append(mods, qm.From("\"moderation_message_logs_messages\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"moderation_message_logs_messages\".*"})
	}

	return moderationMessageLogsMessageQuery{q}
}

// FindModerationMessageLogsMessageG retrieves a single record by ID.
func FindModerationMessageLogsMessageG(ctx context.Context, iD int64, selectCols ...string) (*ModerationMessageLogsMessage, error) {
	return FindModerationMessageLogsMessage(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindModerationMessageLogsMessage retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindModerationMessageLogsMessage(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*ModerationMessageLogsMessage, error) {
	moderationMessageLogsMessageObj := &ModerationMessageLogsMessage{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"moderation_message_logs_messages\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, moderationMessageLogsMessageObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from moderation_message_logs_messages")
	}

	return moderationMessageLogsMessageObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *ModerationMessageLogsMessage) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *ModerationMessageLogsMessage) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no moderation_message_logs_messages provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(moderationMessageLogsMessageColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	moderationMessageLogsMessageInsertCacheMut.RLock()
	cache, cached := moderationMessageLogsMessageInsertCache[key]
	moderationMessageLogsMessageInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			moderationMessageLogsMessageAllColumns,
			moderationMessageLogsMessageColumnsWithDefault,
			moderationMessageLogsMessageColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(moderationMessageLogsMessageType, moderationMessageLogsMessageMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(moderationMessageLogsMessageType, moderationMessageLogsMessageMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"moderation_message_logs_messages\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"moderation_message_logs_messages\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into moderation_message_logs_messages")
	}

	if !cached {
		moderationMessageLogsMessageInsertCacheMut.Lock()
		moderationMessageLogsMessageInsertCache[key] = cache
		moderationMessageLogsMessageInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single ModerationMessageLogsMessage record using the global executor.
// See Update for more documentation.
func (o *ModerationMessageLogsMessage) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the ModerationMessageLogsMessage.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *ModerationMessageLogsMessage) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	moderationMessageLogsMessageUpdateCacheMut.RLock()
	cache, cached := moderationMessageLogsMessageUpdateCache[key]
	moderationMessageLogsMessageUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			moderationMessageLogsMessageAllColumns,
			moderationMessageLogsMessagePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update moderation_message_logs_messages, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"moderation_message_logs_messages\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, moderationMessageLogsMessagePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(moderationMessageLogsMessageType, moderationMessageLogsMessageMapping, append(wl, moderationMessageLogsMessagePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update moderation_message_logs_messages row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for moderation_message_logs_messages")
	}

	if !cached {
		moderationMessageLogsMessageUpdateCacheMut.Lock()
		moderationMessageLogsMessageUpdateCache[key] = cache
		moderationMessageLogsMessageUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q moderationMessageLogsMessageQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q moderationMessageLogsMessageQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for moderation_message_logs_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for moderation_message_logs_messages")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o ModerationMessageLogsMessageSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ModerationMessageLogsMessageSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationMessageLogsMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"moderation_message_logs_messages\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, moderationMessageLogsMessagePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in moderationMessageLogsMessage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all moderationMessageLogsMessage")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *ModerationMessageLogsMessage) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *ModerationMessageLogsMessage) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no moderation_message_logs_messages provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(moderationMessageLogsMessageColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	moderationMessageLogsMessageUpsertCacheMut.RLock()
	cache, cached := moderationMessageLogsMessageUpsertCache[key]
	moderationMessageLogsMessageUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			moderationMessageLogsMessageAllColumns,
			moderationMessageLogsMessageColumnsWithDefault,
			moderationMessageLogsMessageColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			moderationMessageLogsMessageAllColumns,
			moderationMessageLogsMessagePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert moderation_message_logs_messages, could not build update column list")
		}

		ret := strmangle.SetComplement(moderationMessageLogsMessageAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(moderationMessageLogsMessagePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert moderation_message_logs_messages, could not build conflict column list")
			}

			conflict = make([]string, len(moderationMessageLogsMessagePrimaryKeyColumns))
			copy(conflict, moderationMessageLogsMessagePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"moderation_message_logs_messages\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(moderationMessageLogsMessageType, moderationMessageLogsMessageMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(moderationMessageLogsMessageType, moderationMessageLogsMessageMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert moderation_message_logs_messages")
	}

	if !cached {
		moderationMessageLogsMessageUpsertCacheMut.Lock()
		moderationMessageLogsMessageUpsertCache[key] = cache
		moderationMessageLogsMessageUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single ModerationMessageLogsMessage record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *ModerationMessageLogsMessage) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single ModerationMessageLogsMessage record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *ModerationMessageLogsMessage) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no ModerationMessageLogsMessage provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), moderationMessageLogsMessagePrimaryKeyMapping)
	sql := "DELETE FROM \"moderation_message_logs_messages\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from moderation_message_logs_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for moderation_message_logs_messages")
	}

	return rowsAff, nil
}

func (q moderationMessageLogsMessageQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q moderationMessageLogsMessageQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no moderationMessageLogsMessageQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderation_message_logs_messages")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_message_logs_messages")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o ModerationMessageLogsMessageSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ModerationMessageLogsMessageSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationMessageLogsMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"moderation_message_logs_messages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationMessageLogsMessagePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from moderationMessageLogsMessage slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for moderation_message_logs_messages")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *ModerationMessageLogsMessage) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no ModerationMessageLogsMessage provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *ModerationMessageLogsMessage) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindModerationMessageLogsMessage(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationMessageLogsMessageSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty ModerationMessageLogsMessageSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ModerationMessageLogsMessageSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ModerationMessageLogsMessageSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), moderationMessageLogsMessagePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"moderation_message_logs_messages\".* FROM \"moderation_message_logs_messages\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, moderationMessageLogsMessagePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ModerationMessageLogsMessageSlice")
	}

	*o = slice

	return nil
}

// ModerationMessageLogsMessageExistsG checks if the ModerationMessageLogsMessage row exists.
func ModerationMessageLogsMessageExistsG(ctx context.Context, iD int64) (bool, error) {
	return ModerationMessageLogsMessageExists(ctx, boil.GetContextDB(), iD)
}

// ModerationMessageLogsMessageExists checks if the ModerationMessageLogsMessage row exists.
func ModerationMessageLogsMessageExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"moderation_message_logs_messages\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if moderation_message_logs_messages exists")
	}

	return exists, nil
}

// Exists checks if the ModerationMessageLogsMessage row exists.
func (o *ModerationMessageLogsMessage) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ModerationMessageLogsMessageExists(ctx, exec, o.ID)
}
