// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// NotificationsConfig is an object representing the database table.
type NotificationsConfig struct {
	GuildID            string `boil:"guild_id" json:"guild_id" toml:"guild_id" yaml:"guild_id"`
	JoinServerChannel  string `boil:"join_server_channel" json:"join_server_channel" toml:"join_server_channel" yaml:"join_server_channel"`
	JoinServerMessage  string `boil:"join_server_message" json:"join_server_message" toml:"join_server_message" yaml:"join_server_message"`
	LeaveServerChannel string `boil:"leave_server_channel" json:"leave_server_channel" toml:"leave_server_channel" yaml:"leave_server_channel"`
	LeaveServerMessage string `boil:"leave_server_message" json:"leave_server_message" toml:"leave_server_message" yaml:"leave_server_message"`

	R *notificationsConfigR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L notificationsConfigL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NotificationsConfigColumns = struct {
	GuildID            string
	JoinServerChannel  string
	JoinServerMessage  string
	LeaveServerChannel string
	LeaveServerMessage string
}{
	GuildID:            "guild_id",
	JoinServerChannel:  "join_server_channel",
	JoinServerMessage:  "join_server_message",
	LeaveServerChannel: "leave_server_channel",
	LeaveServerMessage: "leave_server_message",
}

var NotificationsConfigTableColumns = struct {
	GuildID            string
	JoinServerChannel  string
	JoinServerMessage  string
	LeaveServerChannel string
	LeaveServerMessage string
}{
	GuildID:            "notifications_config.guild_id",
	JoinServerChannel:  "notifications_config.join_server_channel",
	JoinServerMessage:  "notifications_config.join_server_message",
	LeaveServerChannel: "notifications_config.leave_server_channel",
	LeaveServerMessage: "notifications_config.leave_server_message",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod      { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod    { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod   { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod   { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) SIMILAR(x string) qm.QueryMod { return qm.Where(w.field+" SIMILAR TO ?", x) }
func (w whereHelperstring) NSIMILAR(x string) qm.QueryMod {
	return qm.Where(w.field+" NOT SIMILAR TO ?", x)
}
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var NotificationsConfigWhere = struct {
	GuildID            whereHelperstring
	JoinServerChannel  whereHelperstring
	JoinServerMessage  whereHelperstring
	LeaveServerChannel whereHelperstring
	LeaveServerMessage whereHelperstring
}{
	GuildID:            whereHelperstring{field: "\"notifications_config\".\"guild_id\""},
	JoinServerChannel:  whereHelperstring{field: "\"notifications_config\".\"join_server_channel\""},
	JoinServerMessage:  whereHelperstring{field: "\"notifications_config\".\"join_server_message\""},
	LeaveServerChannel: whereHelperstring{field: "\"notifications_config\".\"leave_server_channel\""},
	LeaveServerMessage: whereHelperstring{field: "\"notifications_config\".\"leave_server_message\""},
}

// NotificationsConfigRels is where relationship names are stored.
var NotificationsConfigRels = struct {
}{}

// notificationsConfigR is where relationships are stored.
type notificationsConfigR struct {
}

// NewStruct creates a new relationship struct
func (*notificationsConfigR) NewStruct() *notificationsConfigR {
	return &notificationsConfigR{}
}

// notificationsConfigL is where Load methods for each relationship are stored.
type notificationsConfigL struct{}

var (
	notificationsConfigAllColumns            = []string{"guild_id", "join_server_channel", "join_server_message", "leave_server_channel", "leave_server_message"}
	notificationsConfigColumnsWithoutDefault = []string{"guild_id"}
	notificationsConfigColumnsWithDefault    = []string{"join_server_channel", "join_server_message", "leave_server_channel", "leave_server_message"}
	notificationsConfigPrimaryKeyColumns     = []string{"guild_id"}
	notificationsConfigGeneratedColumns      = []string{}
)

type (
	// NotificationsConfigSlice is an alias for a slice of pointers to NotificationsConfig.
	// This should almost always be used instead of []NotificationsConfig.
	NotificationsConfigSlice []*NotificationsConfig

	notificationsConfigQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	notificationsConfigType                 = reflect.TypeOf(&NotificationsConfig{})
	notificationsConfigMapping              = queries.MakeStructMapping(notificationsConfigType)
	notificationsConfigPrimaryKeyMapping, _ = queries.BindMapping(notificationsConfigType, notificationsConfigMapping, notificationsConfigPrimaryKeyColumns)
	notificationsConfigInsertCacheMut       sync.RWMutex
	notificationsConfigInsertCache          = make(map[string]insertCache)
	notificationsConfigUpdateCacheMut       sync.RWMutex
	notificationsConfigUpdateCache          = make(map[string]updateCache)
	notificationsConfigUpsertCacheMut       sync.RWMutex
	notificationsConfigUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// OneG returns a single notificationsConfig record from the query using the global executor.
func (q notificationsConfigQuery) OneG(ctx context.Context) (*NotificationsConfig, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single notificationsConfig record from the query.
func (q notificationsConfigQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NotificationsConfig, error) {
	o := &NotificationsConfig{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for notifications_config")
	}

	return o, nil
}

// AllG returns all NotificationsConfig records from the query using the global executor.
func (q notificationsConfigQuery) AllG(ctx context.Context) (NotificationsConfigSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all NotificationsConfig records from the query.
func (q notificationsConfigQuery) All(ctx context.Context, exec boil.ContextExecutor) (NotificationsConfigSlice, error) {
	var o []*NotificationsConfig

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NotificationsConfig slice")
	}

	return o, nil
}

// CountG returns the count of all NotificationsConfig records in the query using the global executor
func (q notificationsConfigQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all NotificationsConfig records in the query.
func (q notificationsConfigQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count notifications_config rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q notificationsConfigQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q notificationsConfigQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if notifications_config exists")
	}

	return count > 0, nil
}

// NotificationsConfigs retrieves all the records using an executor.
func NotificationsConfigs(mods ...qm.QueryMod) notificationsConfigQuery {
	mods = append(mods, qm.From("\"notifications_config\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"notifications_config\".*"})
	}

	return notificationsConfigQuery{q}
}

// FindNotificationsConfigG retrieves a single record by ID.
func FindNotificationsConfigG(ctx context.Context, guildID string, selectCols ...string) (*NotificationsConfig, error) {
	return FindNotificationsConfig(ctx, boil.GetContextDB(), guildID, selectCols...)
}

// FindNotificationsConfig retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNotificationsConfig(ctx context.Context, exec boil.ContextExecutor, guildID string, selectCols ...string) (*NotificationsConfig, error) {
	notificationsConfigObj := &NotificationsConfig{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"notifications_config\" where \"guild_id\"=$1", sel,
	)

	q := queries.Raw(query, guildID)

	err := q.Bind(ctx, exec, notificationsConfigObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from notifications_config")
	}

	return notificationsConfigObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *NotificationsConfig) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NotificationsConfig) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no notifications_config provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(notificationsConfigColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	notificationsConfigInsertCacheMut.RLock()
	cache, cached := notificationsConfigInsertCache[key]
	notificationsConfigInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			notificationsConfigAllColumns,
			notificationsConfigColumnsWithDefault,
			notificationsConfigColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(notificationsConfigType, notificationsConfigMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(notificationsConfigType, notificationsConfigMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"notifications_config\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"notifications_config\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into notifications_config")
	}

	if !cached {
		notificationsConfigInsertCacheMut.Lock()
		notificationsConfigInsertCache[key] = cache
		notificationsConfigInsertCacheMut.Unlock()
	}

	return nil
}

// UpdateG a single NotificationsConfig record using the global executor.
// See Update for more documentation.
func (o *NotificationsConfig) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the NotificationsConfig.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NotificationsConfig) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	notificationsConfigUpdateCacheMut.RLock()
	cache, cached := notificationsConfigUpdateCache[key]
	notificationsConfigUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			notificationsConfigAllColumns,
			notificationsConfigPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update notifications_config, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"notifications_config\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, notificationsConfigPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(notificationsConfigType, notificationsConfigMapping, append(wl, notificationsConfigPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update notifications_config row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for notifications_config")
	}

	if !cached {
		notificationsConfigUpdateCacheMut.Lock()
		notificationsConfigUpdateCache[key] = cache
		notificationsConfigUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (q notificationsConfigQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q notificationsConfigQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for notifications_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for notifications_config")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o NotificationsConfigSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NotificationsConfigSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationsConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"notifications_config\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, notificationsConfigPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in notificationsConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all notificationsConfig")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *NotificationsConfig) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NotificationsConfig) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no notifications_config provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(notificationsConfigColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	notificationsConfigUpsertCacheMut.RLock()
	cache, cached := notificationsConfigUpsertCache[key]
	notificationsConfigUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			notificationsConfigAllColumns,
			notificationsConfigColumnsWithDefault,
			notificationsConfigColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			notificationsConfigAllColumns,
			notificationsConfigPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert notifications_config, could not build update column list")
		}

		ret := strmangle.SetComplement(notificationsConfigAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(notificationsConfigPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert notifications_config, could not build conflict column list")
			}

			conflict = make([]string, len(notificationsConfigPrimaryKeyColumns))
			copy(conflict, notificationsConfigPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"notifications_config\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(notificationsConfigType, notificationsConfigMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(notificationsConfigType, notificationsConfigMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert notifications_config")
	}

	if !cached {
		notificationsConfigUpsertCacheMut.Lock()
		notificationsConfigUpsertCache[key] = cache
		notificationsConfigUpsertCacheMut.Unlock()
	}

	return nil
}

// DeleteG deletes a single NotificationsConfig record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *NotificationsConfig) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single NotificationsConfig record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NotificationsConfig) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NotificationsConfig provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), notificationsConfigPrimaryKeyMapping)
	sql := "DELETE FROM \"notifications_config\" WHERE \"guild_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from notifications_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for notifications_config")
	}

	return rowsAff, nil
}

func (q notificationsConfigQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q notificationsConfigQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no notificationsConfigQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from notifications_config")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for notifications_config")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o NotificationsConfigSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NotificationsConfigSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationsConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"notifications_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notificationsConfigPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from notificationsConfig slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for notifications_config")
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *NotificationsConfig) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: no NotificationsConfig provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NotificationsConfig) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNotificationsConfig(ctx, exec, o.GuildID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotificationsConfigSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("models: empty NotificationsConfigSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotificationsConfigSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NotificationsConfigSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationsConfigPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"notifications_config\".* FROM \"notifications_config\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, notificationsConfigPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NotificationsConfigSlice")
	}

	*o = slice

	return nil
}

// NotificationsConfigExistsG checks if the NotificationsConfig row exists.
func NotificationsConfigExistsG(ctx context.Context, guildID string) (bool, error) {
	return NotificationsConfigExists(ctx, boil.GetContextDB(), guildID)
}

// NotificationsConfigExists checks if the NotificationsConfig row exists.
func NotificationsConfigExists(ctx context.Context, exec boil.ContextExecutor, guildID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"notifications_config\" where \"guild_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, guildID)
	}
	row := exec.QueryRowContext(ctx, sql, guildID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if notifications_config exists")
	}

	return exists, nil
}

// Exists checks if the NotificationsConfig row exists.
func (o *NotificationsConfig) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return NotificationsConfigExists(ctx, exec, o.GuildID)
}
